title: "FLwatch"
#title_tagline: "Glucose & Insulin Graphs for iPhone & Apple Watch"
description: "FLwatch is a free open-source app showing glucose, insulin-on-board and activity graphs with widgets on iPhone and Apple Watch using LibreLinkUp data."
screenshots_string: Screenshots
url: "https://flwatch.app"
baseurl: ""
permalink: pretty
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
theme: null
lang: en
github:
  is_project_page: true
  repository_url: https://github.com/poml88/FLwatch

# SEO & App
appstore_id: "6670172928"  # Apple App Store ID
appstore_url: "https://apps.apple.com/app/id6670172928"
github_repo: "https://github.com/poml88/FLwatch"

# Build settings
exclude:
  - "README.md"
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  
webmaster_verifications:
  google: 78lgumo9gd4zCWy_r2QEEfi_QEXoe2A7Ln6BcUF8NNk